name: Instagram Automation

on:
  schedule:
    - cron: "0 17 * * *"  # Runs every day at 10:00 PM PKT (17:00 UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          playwright install
          npx playwright install-deps

      # 🔎 Debug step (remove after testing)
      - name: Debug IG secrets
        run: |
          echo "IG_USER length: ${#IG_USER}"
          if [ -z "$IG_PASS" ]; then 
            echo "IG_PASS set: no"
          else 
            echo "IG_PASS set: yes"
          fi
        env:
          IG_USER: ${{ secrets.IG_USER }}
          IG_PASS: ${{ secrets.IG_PASS }}

      - name: Run bot
        env:
          IG_USER: ${{ secrets.IG_USER }}
          IG_PASS: ${{ secrets.IG_PASS }}
        run: |
          python main.py
