name: Instagram Automation

on:
  schedule:
    # Runs every day at 10:00 PM PKT (17:00 UTC)
    - cron: "0 17 * * *"
  workflow_dispatch: # manual run possible

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install
          npx playwright install-deps

      # ✅ Write storage_state.json from secret
      - name: Write storage_state.json
        run: |
          if [ -n "$IG_STORAGE_STATE_JSON" ]; then
            echo "$IG_STORAGE_STATE_JSON" > storage_state.json
            echo "✅ storage_state.json written"
          else
            echo "❌ IG_STORAGE_STATE_JSON not set"
            exit 1
          fi
        env:
          IG_STORAGE_STATE_JSON: ${{ secrets.IG_STORAGE_STATE_JSON }}

      # 🔍 Preview (only first 200 chars, safe)
      - name: Preview storage_state.json
        run: |
          head -c 200 storage_state.json
          echo -e "\n✅ storage_state.json exists (showing first 200 chars)"

      # ▶️ Run the bot
      - name: Run bot
        env:
          IG_STORAGE_STATE_PATH: storage_state.json
        run: |
          python main.py
